server:
  port: 1111
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/
    eviction-interval-timer-in-ms:instance: 4000
    hostname: localhost
